### PR TITLE
added Dockerfile and docker-compose.yaml for self-hosting the generator.

### PR DESCRIPTION
**Pull request by sarangcr03**
Deploys a Docker container running an Apache web server that hosts the Generator application. The Generator can be accessed at http://localhost:9090/edit.html. Ensure that the Docker container maps its internal port (where Apache listens, port 80 in this case) to port 9090 on the host machine. external port can be changed to whatever is available.

### CODE REVIEW

**Comment by nonsalant** [comment]
Hi and thanks for the PR.

Is it possible to put the files inside the generator folder? Would like to keep that compartmentalized.

**Comment by sarangcr03** [comment]
Hi, 
It can be placed in the generator folder or if you want it separated, it can be put in a separate docker folder. Let me know which one you prefer. I'll rewrite the Dockerfile accordingly.

**Comment by sarangcr03** [comment]
I have updated the readme with instructions to deploy with docker and docker-compose.  I have also added a .dockerignore and a docker-compose file for running the contract app with nginx proxy manager.

**Comment by nonsalant** [comment]
Thank you. Merged!

**Pull request merged**
